# model
image_size: 512
num_frames: 65
use_image_num: 16
frame_stride: 1
model_version: "LatteT2V-XL/122"
pretrained_model_path: "path/to/pretrained/model"
vae_checkpoint: "models/ae/causal_vae_488.ckpt"
sd_scale_factor: 0.18215
enable_flash_attention: True
use_recompute: True

# precision
dtype: "fp16"
amp_level: "O1"
init_loss_scale: 65536

# training hyper-params
scheduler: "constant"
start_learning_rate: 2.e-5
end_learning_rate: 2.e-5
warmup_steps: 0   # TODO: ablate

batch_size: 2
clip_grad: True
max_grad_norm: 1.0
use_ema: False

optim: "adamw"
optim_eps: 1.e-8
weight_decay: 1e-2

epochs: 2000
ckpt_save_interval: 500
ckpt_max_keep: 3
